version: '3'

services:
  # Configuración del contenedor de Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    user: "1000:1000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel-net
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  # Configuración del contenedor de MySQL
  mysql:
    image: mysql:8.0
    container_name: laravel-db
    volumes:
      - ./db/mysql_data:/var/lib/mysql  # Mapea la carpeta del contenedor al host
      - ./db/mysql_config:/etc/mysql/conf.d  # Mapea configuraciones personalizadas, si las tienes
    environment:
      MYSQL_ROOT_PASSWORD: x0g5-OLs3-vcDj-8fl2-5hIJ
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: x0g5-OLs3-vcDj-8fl2-5hIJ
    ports:
      - "3306:3306"
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge
